//
//  UIDevice(Identifier).h
//  UIDeviceAddition
//
//  Created by Georg Kitz on 20.08.11.
//  Copyright 2011 Aurora Apps. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

@interface UIDevice (IdentifierAddition)

/*
 *  add by wangwei34
 *  @description new method to get unique identifier for ads,
 *               in iOS6 or later, it's the identifier from AdSupport.fw, otherwise it's cuid
 */

- (NSString *) adsIdentifier;

/*
 *  add by wangwei34
 *  @description new method to get unique identifier, generated by MTJ
 */

- (NSString *) cuid;
- (NSString *) md5cuid_with_salt:(NSString*)salt;   // default salt is “cjjmvideo”

/*
 * @method uniqueDeviceIdentifier
 * @description use this method when you need a unique identifier in one app.
 * It generates a hash from the MAC-address in combination with the bundle identifier
 * of your app.
 */

- (NSString *) uniqueDeviceIdentifier;

/*
 * @method uniqueGlobalDeviceIdentifier
 * @description use this method when you need a unique global identifier to track a device
 * with multiple apps. as example a advertising network will use this method to track the device
 * from different apps.
 * It generates a hash from the MAC-address only.
 */

//- (NSString *) uniqueGlobalDeviceIdentifier;

@end

@interface UIDevice (idfa)

// project should provide the IDFA if needed.
- (NSString *) adsIdentifierImpl;

@end